package com.reps100.app;

import java.util.*;

public final class ExerciseData {
  public static final class Exercise {
    public final String name,muscle,equipment,movement,difficulty,photo;
    public Exercise(String n,String m,String e,String mv,String d,String p){name=n;muscle=m;equipment=e;movement=mv;difficulty=d;photo=p;}
  }
  public static final List<Exercise> ALL = Collections.unmodifiableList(Arrays.asList(
    new Exercise("Push-Up", "Chest", "Bodyweight", "Push", "", "card_push_up"),
    new Exercise("Incline Push-Up", "Chest", "Bodyweight", "Push", "", "card_incline_push_up"),
    new Exercise("Decline Push-Up", "Chest", "Bodyweight", "Push", "", "card_decline_push_up"),
    new Exercise("Diamond Push-Up", "Chest", "Bodyweight", "Push", "", "card_diamond_push_up"),
    new Exercise("Wide Push-Up", "Chest", "Bodyweight", "Push", "", "card_wide_push_up"),
    new Exercise("Bench Press", "Chest", "Barbell", "Push", "", "card_bench_press"),
    new Exercise("Incline Bench Press", "Chest", "Barbell", "Push", "", "card_incline_bench_press"),
    new Exercise("Decline Bench Press", "Chest", "Barbell", "Push", "", "card_decline_bench_press"),
    new Exercise("Close-Grip Bench Press", "Chest", "Barbell", "Push", "", "card_close_grip_bench_press"),
    new Exercise("Dumbbell Bench Press", "Chest", "Dumbbell", "Push", "", "card_dumbbell_bench_press"),
    new Exercise("Incline Dumbbell Press", "Chest", "Dumbbell", "Push", "", "card_incline_dumbbell_press"),
    new Exercise("Dumbbell Fly", "Chest", "Dumbbell", "Push", "", "card_dumbbell_fly"),
    new Exercise("Cable Fly", "Chest", "Machine/Cable", "Push", "", "card_cable_fly"),
    new Exercise("Machine Chest Press Pec Deck", "Shoulders", "Machine", "Push", "", "card_machine_chest_press_pec_deck"),
    new Exercise("Dips", "Chest", "Bodyweight", "Push", "", "card_dips"),
    new Exercise("Triceps Dips On A Bench", "Triceps", "Bodyweight", "Push", "", "card_triceps_dips_on_a_bench"),
    new Exercise("Pull Up", "Back", "Bodyweight", "Pull", "", "card_pull_up"),
    new Exercise("Chin Up", "Full Body", "Bodyweight", "Squat", "", "card_chin_up"),
    new Exercise("Lat Pulldown", "Back", "Machine/Cable", "Pull", "", "card_lat_pulldown"),
    new Exercise("Straight Arm Pulldown", "Back", "Bodyweight", "Pull", "", "card_straight_arm_pulldown"),
    new Exercise("Barbell Row", "Back", "Barbell", "Pull", "", "card_barbell_row"),
    new Exercise("Pendlay Row", "Back", "Barbell", "Pull", "", "card_pendlay_row"),
    new Exercise("Dumbbell Row", "Back", "Dumbbell", "Pull", "", "card_dumbbell_row"),
    new Exercise("Chest-Supported Row", "Back", "Dumbbell", "Pull", "", "card_chest_supported_row"),
    new Exercise("Seated Cable Row", "Back", "Machine/Cable", "Pull", "", "card_seated_cable_row"),
    new Exercise("Face Pull", "Back", "Machine/Cable", "Pull", "", "card_face_pull"),
    new Exercise("Inverted Row", "Back", "Bodyweight", "Pull", "", "card_inverted_row"),
    new Exercise("Back Squat", "Quads", "Barbell", "Squat", "", "card_back_squat"),
    new Exercise("Front Squat", "Quads", "Barbell", "Squat", "", "card_front_squat"),
    new Exercise("Goblet Squat", "Quads", "Dumbbell", "Squat", "", "card_goblet_squat"),
    new Exercise("Dumbbell Squat", "Quads", "Dumbbell", "Squat", "", "card_dumbbell_squat"),
    new Exercise("Hack Squat", "Quads", "Machine", "Squat", "", "card_hack_squat"),
    new Exercise("Leg Press", "Quads", "Machine", "Squat", "", "card_leg_press"),
    new Exercise("Leg Extension", "Quads", "Machine", "Knee Extension", "", "card_leg_extension"),
    new Exercise("Dumbbell Lunges", "Quads", "Dumbbell", "Lunge", "", "card_dumbbell_lunges"),
    new Exercise("Reverse Lunge", "Quads", "Dumbbell", "Lunge", "", "card_reverse_lunge"),
    new Exercise("Ab Wheel Rollout", "Core", "Bodyweight", "Core", "", "card_ab_wheel_rollout"),
    new Exercise("Arnold Press", "Shoulders", "Dumbbell", "Push", "", "card_arnold_press"),
    new Exercise("Barbell Calf Raise", "Full Body", "Barbell", "Squat", "", "card_barbell_calf_raise"),
    new Exercise("Barbell Curl", "Biceps", "Barbell", "Curl", "", "card_barbell_curl"),
    new Exercise("Barbell Overhead Press", "Shoulders", "Barbell", "Push", "", "card_barbell_overhead_press"),
    new Exercise("Barbell Shrugs", "Traps", "Barbell", "Pull", "", "card_barbell_shrugs"),
    new Exercise("Barbell Snatch", "Full Body", "Barbell", "Full Body", "", "card_barbell_snatch"),
    new Exercise("Bicycle Crunch", "Core", "Bodyweight", "Core", "", "card_bicycle_crunch"),
    new Exercise("Bird Dog", "Core", "Bodyweight", "Core", "", "card_bird_dog"),
    new Exercise("Bodyweight Kickbacks", "Glutes", "Bodyweight", "Hinge", "", "card_bodyweight_kickbacks"),
    new Exercise("Bodyweight Lunge", "Quads", "Bodyweight", "Lunge", "", "card_bodyweight_lunge"),
    new Exercise("Bodyweight Reverse Lunge", "Quads", "Bodyweight", "Lunge", "", "card_bodyweight_reverse_lunge"),
    new Exercise("Bodyweight Side Lunge", "Quads", "Bodyweight", "Lunge", "", "card_bodyweight_side_lunge"),
    new Exercise("Bodyweight Single Leg Calf Raise", "Full Body", "Bodyweight", "Squat", "", "card_bodyweight_single_leg_calf_raise"),
    new Exercise("Bodyweight Squat", "Quads", "Bodyweight", "Squat", "", "card_bodyweight_squat"),
    new Exercise("Bodyweight Step-Up", "Quads", "Bodyweight", "Lunge", "", "card_bodyweight_step_up"),
    new Exercise("Bodyweight Sumo Squat", "Quads", "Bodyweight", "Squat", "", "card_bodyweight_sumo_squat"),
    new Exercise("Box Jumps", "Quads", "Bodyweight", "Squat", "", "card_box_jumps"),
    new Exercise("Bulgarian Split Squat", "Quads", "Dumbbell", "Lunge", "", "card_bulgarian_split_squat"),
    new Exercise("Burpee", "Full Body", "Bodyweight", "Full Body", "", "card_burpee"),
    new Exercise("Cable Curl", "Biceps", "Machine/Cable", "Curl", "", "card_cable_curl"),
    new Exercise("Cable Kickback", "Glutes", "Machine/Cable", "Hinge", "", "card_cable_kickback"),
    new Exercise("Cable Lateral Raise", "Shoulders", "Machine/Cable", "Raise", "", "card_cable_lateral_raise"),
    new Exercise("Cable Wood Chop", "Core", "Machine/Cable", "Core", "", "card_cable_wood_chop"),
    new Exercise("Concentration Curl", "Biceps", "Dumbbell", "Curl", "", "card_concentration_curl"),
    new Exercise("Conventional Deadlift", "Hamstrings", "Barbell", "Hinge", "", "card_conventional_deadlift"),
    new Exercise("Crunches", "Core", "Bodyweight", "Core", "", "card_crunches"),
    new Exercise("Dead Bug", "Core", "Bodyweight", "Core", "", "card_dead_bug"),
    new Exercise("Donkey Kicks", "Glutes", "Bodyweight", "Hinge", "", "card_donkey_kicks"),
    new Exercise("Dumbbell Calf Raise", "Calves", "Dumbbell", "Calf Raise", "", "card_dumbbell_calf_raise"),
    new Exercise("Dumbbell Curl", "Biceps", "Dumbbell", "Curl", "", "card_dumbbell_curl"),
    new Exercise("Dumbbell Leg Curl", "Hamstrings", "Dumbbell", "Hinge", "", "card_dumbbell_leg_curl"),
    new Exercise("Dumbbell Romanian Deadlift", "Hamstrings", "Dumbbell", "Hinge", "", "card_dumbbell_romanian_deadlift"),
    new Exercise("Dumbbell Shoulder Press", "Shoulders", "Dumbbell", "Push", "", "card_dumbbell_shoulder_press"),
    new Exercise("Dumbbell Shrugs", "Traps", "Dumbbell", "Pull", "", "card_dumbbell_shrugs"),
    new Exercise("Dumbbell Skull Crusher", "Triceps", "Dumbbell", "Push", "", "card_dumbbell_skull_crusher"),
    new Exercise("Dumbbell Thruster", "Full Body", "Dumbbell", "Full Body", "", "card_dumbbell_thruster"),
    new Exercise("Forward-Back Jumps", "Quads", "Bodyweight", "Squat", "", "card_forward_back_jumps"),
    new Exercise("Front Raise", "Shoulders", "Dumbbell", "Raise", "", "card_front_raise"),
    new Exercise("Glute Bridge", "Glutes", "Bodyweight", "Hinge", "", "card_glute_bridge"),
    new Exercise("Good Morning", "Hamstrings", "Barbell", "Hinge", "", "card_good_morning"),
    new Exercise("Hammer Curl", "Biceps", "Dumbbell", "Curl", "", "card_hammer_curl"),
    new Exercise("Hanging Knee Raise", "Core", "Bodyweight", "Core", "", "card_hanging_knee_raise"),
    new Exercise("Hanging Leg Raise", "Core", "Bodyweight", "Core", "", "card_hanging_leg_raise"),
    new Exercise("High Knees", "Full Body", "Bodyweight", "Full Body", "", "card_high_knees"),
    new Exercise("Hip Abduction", "Glutes", "Machine", "Abduction", "", "card_hip_abduction"),
    new Exercise("Hip Adduction", "Glutes", "Machine", "Adduction", "", "card_hip_adduction"),
    new Exercise("Hip Thrust", "Glutes", "Barbell", "Hinge", "", "card_hip_thrust"),
    new Exercise("Incline Dumbbell Curl", "Biceps", "Dumbbell", "Curl", "", "card_incline_dumbbell_curl"),
    new Exercise("Jumping Jack", "Full Body", "Bodyweight", "Full Body", "", "card_jumping_jack"),
    new Exercise("Kettlebell Clean", "Full Body", "Kettlebell", "Full Body", "", "card_kettlebell_clean"),
    new Exercise("Kettlebell Deadlift", "Hamstrings", "Kettlebell", "Hinge", "", "card_kettlebell_deadlift"),
    new Exercise("Kettlebell Goblet Squat", "Quads", "Kettlebell", "Squat", "", "card_kettlebell_goblet_squat"),
    new Exercise("Kettlebell One Arm Press", "Shoulders", "Kettlebell", "Push", "", "card_kettlebell_one_arm_press"),
    new Exercise("Kettlebell Snatch", "Full Body", "Kettlebell", "Full Body", "", "card_kettlebell_snatch"),
    new Exercise("Kettlebell Swing", "Full Body", "Kettlebell", "Hinge", "", "card_kettlebell_swing"),
    new Exercise("Kettlebell Thruster", "Full Body", "Kettlebell", "Full Body", "", "card_kettlebell_thruster"),
    new Exercise("Lateral Raise", "Shoulders", "Dumbbell", "Raise", "", "card_lateral_raise"),
    new Exercise("Lying Back Extension", "Back", "Bodyweight", "Pull", "", "card_lying_back_extension"),
    new Exercise("Lying Leg Curl", "Hamstrings", "Machine/Cable", "Knee Flexion", "", "card_lying_leg_curl"),
    new Exercise("Lying Leg Raise", "Core", "Bodyweight", "Core", "", "card_lying_leg_raise"),
    new Exercise("Mountain Climber", "Core", "Bodyweight", "Core", "", "card_mountain_climber"),
    new Exercise("Overhead Cable Tricep Extension", "Triceps", "Machine/Cable", "Push", "", "card_overhead_cable_tricep_extension"),
    new Exercise("Overhead Tricep Extension", "Triceps", "Bodyweight", "Push", "", "card_overhead_tricep_extension"),
    new Exercise("Preacher Curl", "Biceps", "Dumbbell", "Curl", "", "card_preacher_curl"),
    new Exercise("Prone Alternate Back Raise", "Shoulders", "Bodyweight", "Push", "", "card_prone_alternate_back_raise"),
    new Exercise("Rear Delt Fly", "Shoulders", "Dumbbell", "Raise", "", "card_rear_delt_fly"),
    new Exercise("Reverse Crunch", "Core", "Bodyweight", "Core", "", "card_reverse_crunch"),
    new Exercise("Reverse Curl", "Biceps", "Barbell", "Curl", "", "card_reverse_curl"),
    new Exercise("Romanian Deadlift", "Hamstrings", "Barbell", "Hinge", "", "card_romanian_deadlift"),
    new Exercise("Russian Twists", "Core", "Bodyweight", "Core", "", "card_russian_twists"),
    new Exercise("Scissor Kicks", "Core", "Bodyweight", "Core", "", "card_scissor_kicks"),
    new Exercise("Side-to-Side Jumps", "Quads", "Bodyweight", "Squat", "", "card_side_to_side_jumps"),
    new Exercise("Single Leg Glute Bridge", "Glutes", "Bodyweight", "Hinge", "", "card_single_leg_glute_bridge"),
    new Exercise("Single Leg Squat", "Quads", "Bodyweight", "Squat", "", "card_single_leg_squat"),
    new Exercise("Sit-Up", "Core", "Bodyweight", "Core", "", "card_sit_up"),
    new Exercise("Sitting Knee Tucks", "Core", "Bodyweight", "Core", "", "card_sitting_knee_tucks"),
    new Exercise("Squat Jumps", "Quads", "Bodyweight", "Jump", "", "card_squat_jumps"),
    new Exercise("Standing Cable Crunches", "Core", "Bodyweight", "Core", "", "card_standing_cable_crunches"),
    new Exercise("Standing Hip Adduction", "Glutes", "Machine", "Hinge", "", "card_standing_hip_adduction"),
    new Exercise("Standing Hip Kickback", "Glutes", "Bodyweight", "Hinge", "", "card_standing_hip_kickback"),
    new Exercise("Standing Single Leg Deadlift", "Hamstrings", "Barbell", "Hinge", "", "card_standing_single_leg_deadlift"),
    new Exercise("Sumo Deadlift", "Hamstrings", "Barbell", "Hinge", "", "card_sumo_deadlift"),
    new Exercise("Trap Bar Deadlift", "Hamstrings", "Barbell", "Hinge", "", "card_trap_bar_deadlift"),
    new Exercise("Trap Bar Shrugs", "Traps", "Bodyweight", "Pull", "", "card_trap_bar_shrugs"),
    new Exercise("Tricep Kickback", "Triceps", "Bodyweight", "Push", "", "card_tricep_kickback"),
    new Exercise("Tuck Jumps", "Quads", "Bodyweight", "Jump", "", "card_tuck_jumps"),
    new Exercise("Turkish Get-Up", "Full Body", "Kettlebell", "Full Body", "", "card_turkish_get_up"),
    new Exercise("Barbell Upright Row", "Shoulders", "Barbell", "Pull", "", "card_barbell_upright_row"),
    new Exercise("Dumbbell Upright Row", "Shoulders", "Dumbbell", "Pull", "", "card_dumbbell_upright_row"),
    new Exercise("V Push Ups", "Chest", "Bodyweight", "Push", "", "card_v_push_ups"),
    new Exercise("Triceps Pushdown", "Triceps", "Machine/Cable", "Push", "", "card_triceps_pushdown"),
    new Exercise("Superman", "Back", "Bodyweight", "Core", "", "card_superman"),
    new Exercise("V-Ups", "Core", "Bodyweight", "Core", "", "card_v_ups")
  ));
  private ExerciseData() {}
}
