package com.reps100.app;

import java.util.*;

public final class ExerciseData {
  public static final class Exercise {
    public final String name,muscle,equipment,movement,difficulty,photo;
    public Exercise(String n,String m,String e,String mv,String d,String p){name=n;muscle=m;equipment=e;movement=mv;difficulty=d;photo=p;}
  }
  public static final List<Exercise> ALL = Collections.unmodifiableList(Arrays.asList(
    new Exercise("Push-Up", "Chest", "Bodyweight", "Push", "Beginner", "pushup"),
    new Exercise("Incline Push-Up", "Chest", "Bodyweight", "Push", "Beginner", "pushup"),
    new Exercise("Decline Push-Up", "Chest", "Bodyweight", "Push", "Beginner", "pushup"),
    new Exercise("Diamond Push-Up", "Chest", "Bodyweight", "Push", "Beginner", "pushup"),
    new Exercise("Wide Push-Up", "Chest", "Bodyweight", "Push", "Beginner", "pushup"),
    new Exercise("Archer Push-Up", "Chest", "Bodyweight", "Push", "Beginner", "pushup"),
    new Exercise("Bench Press", "Chest", "Dumbbell", "Push", "Beginner", "pushup"),
    new Exercise("Incline Bench Press", "Chest", "Dumbbell", "Push", "Beginner", "pushup"),
    new Exercise("Decline Bench Press", "Chest", "Dumbbell", "Push", "Beginner", "pushup"),
    new Exercise("Close-Grip Bench Press", "Chest", "Dumbbell", "Push", "Beginner", "pushup"),
    new Exercise("Dumbbell Bench Press", "Chest", "Dumbbell", "Push", "Beginner", "pushup"),
    new Exercise("Incline Dumbbell Press", "Chest", "Dumbbell", "Push", "Beginner", "pushup"),
    new Exercise("Dumbbell Fly", "Chest", "Dumbbell", "Push", "Beginner", "pushup"),
    new Exercise("Cable Fly", "Chest", "Dumbbell", "Push", "Beginner", "pushup"),
    new Exercise("Machine Chest Press", "Chest", "Dumbbell", "Push", "Beginner", "pushup"),
    new Exercise("Chest Dip", "Chest", "Dumbbell", "Push", "Beginner", "pushup"),
    new Exercise("Pull-Up", "Back", "Barbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Chin-Up", "Back", "Barbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Assisted Pull-Up", "Back", "Barbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Lat Pulldown", "Back", "Barbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Straight-Arm Pulldown", "Back", "Barbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Barbell Row", "Back", "Barbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Pendlay Row", "Back", "Barbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Dumbbell Row", "Back", "Barbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Chest-Supported Row", "Back", "Barbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Seated Cable Row", "Back", "Barbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Machine Row", "Back", "Barbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Face Pull", "Back", "Barbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Inverted Row", "Back", "Barbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Back Squat", "Quads", "Barbell", "Squat", "Beginner", "deadlift"),
    new Exercise("Front Squat", "Quads", "Barbell", "Squat", "Beginner", "deadlift"),
    new Exercise("Goblet Squat", "Quads", "Barbell", "Squat", "Beginner", "deadlift"),
    new Exercise("Dumbbell Squat", "Quads", "Barbell", "Squat", "Beginner", "deadlift"),
    new Exercise("Hack Squat", "Quads", "Barbell", "Squat", "Beginner", "deadlift"),
    new Exercise("Leg Press", "Quads", "Barbell", "Squat", "Beginner", "deadlift"),
    new Exercise("Leg Extension", "Quads", "Barbell", "Squat", "Beginner", "deadlift"),
    new Exercise("Bulgarian Split Squat", "Quads", "Barbell", "Squat", "Beginner", "deadlift"),
    new Exercise("Walking Lunge", "Quads", "Barbell", "Squat", "Beginner", "deadlift"),
    new Exercise("Reverse Lunge", "Quads", "Barbell", "Squat", "Beginner", "deadlift"),
    new Exercise("Bodyweight Lunge", "Quads", "Barbell", "Squat", "Beginner", "deadlift"),
    new Exercise("Step-Up", "Quads", "Barbell", "Squat", "Beginner", "deadlift"),
    new Exercise("Romanian Deadlift", "Hamstrings", "Barbell", "Hinge", "Beginner", "deadlift"),
    new Exercise("Dumbbell Romanian Deadlift", "Hamstrings", "Barbell", "Hinge", "Beginner", "deadlift"),
    new Exercise("Conventional Deadlift", "Hamstrings", "Barbell", "Hinge", "Beginner", "deadlift"),
    new Exercise("Sumo Deadlift", "Hamstrings", "Barbell", "Hinge", "Beginner", "deadlift"),
    new Exercise("Trap Bar Deadlift", "Hamstrings", "Barbell", "Hinge", "Beginner", "deadlift"),
    new Exercise("Good Morning", "Hamstrings", "Barbell", "Hinge", "Beginner", "deadlift"),
    new Exercise("Lying Leg Curl", "Hamstrings", "Barbell", "Hinge", "Beginner", "deadlift"),
    new Exercise("Seated Leg Curl", "Hamstrings", "Barbell", "Hinge", "Beginner", "deadlift"),
    new Exercise("Nordic Curl", "Hamstrings", "Barbell", "Hinge", "Beginner", "deadlift"),
    new Exercise("Hip Thrust", "Glutes", "Barbell", "Hinge", "Beginner", "deadlift"),
    new Exercise("Glute Bridge", "Glutes", "Barbell", "Hinge", "Beginner", "deadlift"),
    new Exercise("Single-Leg Glute Bridge", "Glutes", "Barbell", "Hinge", "Beginner", "deadlift"),
    new Exercise("Cable Kickback", "Glutes", "Barbell", "Hinge", "Beginner", "deadlift"),
    new Exercise("Hip Abduction", "Glutes", "Barbell", "Hinge", "Beginner", "deadlift"),
    new Exercise("Hip Adduction", "Glutes", "Barbell", "Hinge", "Beginner", "deadlift"),
    new Exercise("Standing Calf Raise", "Calves", "Machine", "Calf Raise", "Beginner", "deadlift"),
    new Exercise("Seated Calf Raise", "Calves", "Machine", "Calf Raise", "Beginner", "deadlift"),
    new Exercise("Dumbbell Calf Raise", "Calves", "Machine", "Calf Raise", "Beginner", "deadlift"),
    new Exercise("Single-Leg Calf Raise", "Calves", "Machine", "Calf Raise", "Beginner", "deadlift"),
    new Exercise("Overhead Press", "Shoulders", "Dumbbell", "Push", "Beginner", "barbellrow"),
    new Exercise("Dumbbell Shoulder Press", "Shoulders", "Dumbbell", "Push", "Beginner", "barbellrow"),
    new Exercise("Arnold Press", "Shoulders", "Dumbbell", "Push", "Beginner", "barbellrow"),
    new Exercise("Lateral Raise", "Shoulders", "Dumbbell", "Push", "Beginner", "barbellrow"),
    new Exercise("Cable Lateral Raise", "Shoulders", "Dumbbell", "Push", "Beginner", "barbellrow"),
    new Exercise("Front Raise", "Shoulders", "Dumbbell", "Push", "Beginner", "barbellrow"),
    new Exercise("Rear Delt Fly", "Shoulders", "Dumbbell", "Push", "Beginner", "barbellrow"),
    new Exercise("Reverse Pec Deck", "Shoulders", "Dumbbell", "Push", "Beginner", "barbellrow"),
    new Exercise("Upright Row", "Shoulders", "Dumbbell", "Push", "Beginner", "barbellrow"),
    new Exercise("Barbell Curl", "Biceps", "Dumbbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Dumbbell Curl", "Biceps", "Dumbbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Hammer Curl", "Biceps", "Dumbbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Incline Dumbbell Curl", "Biceps", "Dumbbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Preacher Curl", "Biceps", "Dumbbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Concentration Curl", "Biceps", "Dumbbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Cable Curl", "Biceps", "Dumbbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Reverse Curl", "Biceps", "Dumbbell", "Pull", "Beginner", "barbellrow"),
    new Exercise("Triceps Pushdown", "Triceps", "Cable", "Push", "Beginner", "pushup"),
    new Exercise("Rope Pushdown", "Triceps", "Cable", "Push", "Beginner", "pushup"),
    new Exercise("Overhead Triceps Extension", "Triceps", "Cable", "Push", "Beginner", "pushup"),
    new Exercise("Cable Overhead Extension", "Triceps", "Cable", "Push", "Beginner", "pushup"),
    new Exercise("Skull Crusher", "Triceps", "Cable", "Push", "Beginner", "pushup"),
    new Exercise("Dumbbell Skull Crusher", "Triceps", "Cable", "Push", "Beginner", "pushup"),
    new Exercise("Close-Grip Push-Up", "Triceps", "Cable", "Push", "Beginner", "pushup"),
    new Exercise("Bench Dip", "Triceps", "Cable", "Push", "Beginner", "pushup"),
    new Exercise("Crunch", "Core", "Bodyweight", "Core", "Beginner", "deadlift"),
    new Exercise("Bicycle Crunch", "Core", "Bodyweight", "Core", "Beginner", "deadlift"),
    new Exercise("Reverse Crunch", "Core", "Bodyweight", "Core", "Beginner", "deadlift"),
    new Exercise("Sit-Up", "Core", "Bodyweight", "Core", "Beginner", "deadlift"),
    new Exercise("Plank", "Core", "Bodyweight", "Core", "Beginner", "deadlift"),
    new Exercise("Side Plank", "Core", "Bodyweight", "Core", "Beginner", "deadlift"),
    new Exercise("Dead Bug", "Core", "Bodyweight", "Core", "Beginner", "deadlift"),
    new Exercise("Bird Dog", "Core", "Bodyweight", "Core", "Beginner", "deadlift"),
    new Exercise("Hanging Knee Raise", "Core", "Bodyweight", "Core", "Beginner", "deadlift"),
    new Exercise("Hanging Leg Raise", "Core", "Bodyweight", "Core", "Beginner", "deadlift"),
    new Exercise("Ab Wheel Rollout", "Core", "Bodyweight", "Core", "Beginner", "deadlift"),
    new Exercise("Cable Wood Chop", "Core", "Bodyweight", "Core", "Beginner", "deadlift"),
    new Exercise("Pallof Press", "Core", "Bodyweight", "Core", "Beginner", "deadlift"),
    new Exercise("Kettlebell Swing", "Full Body", "Kettlebell", "Full Body", "Beginner", "deadlift"),
    new Exercise("Kettlebell Clean", "Full Body", "Kettlebell", "Full Body", "Beginner", "deadlift"),
    new Exercise("Kettlebell Snatch", "Full Body", "Kettlebell", "Full Body", "Beginner", "deadlift"),
    new Exercise("Turkish Get-Up", "Full Body", "Kettlebell", "Full Body", "Beginner", "deadlift"),
    new Exercise("Kettlebell Thruster", "Full Body", "Kettlebell", "Full Body", "Beginner", "deadlift"),
    new Exercise("Dumbbell Thruster", "Full Body", "Kettlebell", "Full Body", "Beginner", "deadlift"),
    new Exercise("Burpee", "Full Body", "Kettlebell", "Full Body", "Beginner", "deadlift"),
    new Exercise("Mountain Climber", "Full Body", "Kettlebell", "Full Body", "Beginner", "deadlift"),
    new Exercise("Jumping Jack", "Full Body", "Kettlebell", "Full Body", "Beginner", "deadlift"),
    new Exercise("High Knees", "Full Body", "Kettlebell", "Full Body", "Beginner", "deadlift"),
    new Exercise("Jump Rope", "Full Body", "Kettlebell", "Full Body", "Beginner", "deadlift"),
    new Exercise("Box Jump", "Full Body", "Kettlebell", "Full Body", "Beginner", "deadlift"),
    new Exercise("Bear Crawl", "Full Body", "Kettlebell", "Full Body", "Beginner", "deadlift"),
    new Exercise("Farmer Carry", "Full Body", "Kettlebell", "Full Body", "Beginner", "deadlift"),
    new Exercise("Suitcase Carry", "Full Body", "Kettlebell", "Full Body", "Beginner", "deadlift"),
    new Exercise("Treadmill Walk", "Cardio", "Machine", "Cardio", "Beginner", "deadlift"),
    new Exercise("Treadmill Run", "Cardio", "Machine", "Cardio", "Beginner", "deadlift"),
    new Exercise("Incline Treadmill Walk", "Cardio", "Machine", "Cardio", "Beginner", "deadlift"),
    new Exercise("Stationary Bike", "Cardio", "Machine", "Cardio", "Beginner", "deadlift"),
    new Exercise("Rowing Machine", "Cardio", "Machine", "Cardio", "Beginner", "deadlift"),
    new Exercise("Elliptical", "Cardio", "Machine", "Cardio", "Beginner", "deadlift"),
    new Exercise("Stair Climber", "Cardio", "Machine", "Cardio", "Beginner", "deadlift"),
    new Exercise("Tempo Push-Up", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Incline Push-Up", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Decline Push-Up", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Diamond Push-Up", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Wide Push-Up", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Archer Push-Up", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Bench Press", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Incline Bench Press", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Decline Bench Press", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Close-Grip Bench Press", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Dumbbell Bench Press", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Incline Dumbbell Press", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Dumbbell Fly", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Cable Fly", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Machine Chest Press", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Chest Dip", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Pull-Up", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Chin-Up", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Assisted Pull-Up", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Lat Pulldown", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Straight-Arm Pulldown", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Barbell Row", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Pendlay Row", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Dumbbell Row", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Chest-Supported Row", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Seated Cable Row", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Machine Row", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Face Pull", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Inverted Row", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Back Squat", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Tempo Front Squat", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Tempo Goblet Squat", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Tempo Dumbbell Squat", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Tempo Hack Squat", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Tempo Leg Press", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Tempo Leg Extension", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Tempo Bulgarian Split Squat", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Tempo Walking Lunge", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Tempo Reverse Lunge", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Tempo Bodyweight Lunge", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Tempo Step-Up", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Tempo Romanian Deadlift", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Tempo Dumbbell Romanian Deadlift", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Tempo Conventional Deadlift", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Tempo Sumo Deadlift", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Tempo Trap Bar Deadlift", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Tempo Good Morning", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Tempo Lying Leg Curl", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Tempo Seated Leg Curl", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Tempo Nordic Curl", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Tempo Hip Thrust", "Glutes", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Tempo Glute Bridge", "Glutes", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Tempo Single-Leg Glute Bridge", "Glutes", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Tempo Cable Kickback", "Glutes", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Tempo Hip Abduction", "Glutes", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Tempo Hip Adduction", "Glutes", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Tempo Standing Calf Raise", "Calves", "Machine", "Calf Raise", "Intermediate", "deadlift"),
    new Exercise("Tempo Seated Calf Raise", "Calves", "Machine", "Calf Raise", "Intermediate", "deadlift"),
    new Exercise("Tempo Dumbbell Calf Raise", "Calves", "Machine", "Calf Raise", "Intermediate", "deadlift"),
    new Exercise("Tempo Single-Leg Calf Raise", "Calves", "Machine", "Calf Raise", "Intermediate", "deadlift"),
    new Exercise("Tempo Overhead Press", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Tempo Dumbbell Shoulder Press", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Tempo Arnold Press", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Tempo Lateral Raise", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Tempo Cable Lateral Raise", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Tempo Front Raise", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Tempo Rear Delt Fly", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Tempo Reverse Pec Deck", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Tempo Upright Row", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Tempo Barbell Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Dumbbell Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Hammer Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Incline Dumbbell Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Preacher Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Concentration Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Cable Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Reverse Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Tempo Triceps Pushdown", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Rope Pushdown", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Overhead Triceps Extension", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Cable Overhead Extension", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Skull Crusher", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Dumbbell Skull Crusher", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Close-Grip Push-Up", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Bench Dip", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Tempo Crunch", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Tempo Bicycle Crunch", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Tempo Reverse Crunch", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Tempo Sit-Up", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Tempo Plank", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Tempo Side Plank", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Tempo Dead Bug", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Tempo Bird Dog", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Tempo Hanging Knee Raise", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Tempo Hanging Leg Raise", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Tempo Ab Wheel Rollout", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Tempo Cable Wood Chop", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Tempo Pallof Press", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Tempo Kettlebell Swing", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Tempo Kettlebell Clean", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Tempo Kettlebell Snatch", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Tempo Turkish Get-Up", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Tempo Kettlebell Thruster", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Tempo Dumbbell Thruster", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Tempo Burpee", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Tempo Mountain Climber", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Tempo Jumping Jack", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Tempo High Knees", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Tempo Jump Rope", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Tempo Box Jump", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Tempo Bear Crawl", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Tempo Farmer Carry", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Tempo Suitcase Carry", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Tempo Treadmill Walk", "Cardio", "Machine", "Cardio", "Intermediate", "deadlift"),
    new Exercise("Tempo Treadmill Run", "Cardio", "Machine", "Cardio", "Intermediate", "deadlift"),
    new Exercise("Tempo Incline Treadmill Walk", "Cardio", "Machine", "Cardio", "Intermediate", "deadlift"),
    new Exercise("Tempo Stationary Bike", "Cardio", "Machine", "Cardio", "Intermediate", "deadlift"),
    new Exercise("Tempo Rowing Machine", "Cardio", "Machine", "Cardio", "Intermediate", "deadlift"),
    new Exercise("Tempo Elliptical", "Cardio", "Machine", "Cardio", "Intermediate", "deadlift"),
    new Exercise("Tempo Stair Climber", "Cardio", "Machine", "Cardio", "Intermediate", "deadlift"),
    new Exercise("Pause Push-Up", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Incline Push-Up", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Decline Push-Up", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Diamond Push-Up", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Wide Push-Up", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Archer Push-Up", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Bench Press", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Incline Bench Press", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Decline Bench Press", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Close-Grip Bench Press", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Dumbbell Bench Press", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Incline Dumbbell Press", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Dumbbell Fly", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Cable Fly", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Machine Chest Press", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Chest Dip", "Chest", "Dumbbell", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Pull-Up", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Chin-Up", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Assisted Pull-Up", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Lat Pulldown", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Straight-Arm Pulldown", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Barbell Row", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Pendlay Row", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Dumbbell Row", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Chest-Supported Row", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Seated Cable Row", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Machine Row", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Face Pull", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Inverted Row", "Back", "Barbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Back Squat", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Pause Front Squat", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Pause Goblet Squat", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Pause Dumbbell Squat", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Pause Hack Squat", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Pause Leg Press", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Pause Leg Extension", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Pause Bulgarian Split Squat", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Pause Walking Lunge", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Pause Reverse Lunge", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Pause Bodyweight Lunge", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Pause Step-Up", "Quads", "Barbell", "Squat", "Intermediate", "deadlift"),
    new Exercise("Pause Romanian Deadlift", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Pause Dumbbell Romanian Deadlift", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Pause Conventional Deadlift", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Pause Sumo Deadlift", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Pause Trap Bar Deadlift", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Pause Good Morning", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Pause Lying Leg Curl", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Pause Seated Leg Curl", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Pause Nordic Curl", "Hamstrings", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Pause Hip Thrust", "Glutes", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Pause Glute Bridge", "Glutes", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Pause Single-Leg Glute Bridge", "Glutes", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Pause Cable Kickback", "Glutes", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Pause Hip Abduction", "Glutes", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Pause Hip Adduction", "Glutes", "Barbell", "Hinge", "Intermediate", "deadlift"),
    new Exercise("Pause Standing Calf Raise", "Calves", "Machine", "Calf Raise", "Intermediate", "deadlift"),
    new Exercise("Pause Seated Calf Raise", "Calves", "Machine", "Calf Raise", "Intermediate", "deadlift"),
    new Exercise("Pause Dumbbell Calf Raise", "Calves", "Machine", "Calf Raise", "Intermediate", "deadlift"),
    new Exercise("Pause Single-Leg Calf Raise", "Calves", "Machine", "Calf Raise", "Intermediate", "deadlift"),
    new Exercise("Pause Overhead Press", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Pause Dumbbell Shoulder Press", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Pause Arnold Press", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Pause Lateral Raise", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Pause Cable Lateral Raise", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Pause Front Raise", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Pause Rear Delt Fly", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Pause Reverse Pec Deck", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Pause Upright Row", "Shoulders", "Dumbbell", "Push", "Intermediate", "barbellrow"),
    new Exercise("Pause Barbell Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Dumbbell Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Hammer Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Incline Dumbbell Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Preacher Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Concentration Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Cable Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Reverse Curl", "Biceps", "Dumbbell", "Pull", "Intermediate", "barbellrow"),
    new Exercise("Pause Triceps Pushdown", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Rope Pushdown", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Overhead Triceps Extension", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Cable Overhead Extension", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Skull Crusher", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Dumbbell Skull Crusher", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Close-Grip Push-Up", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Bench Dip", "Triceps", "Cable", "Push", "Intermediate", "pushup"),
    new Exercise("Pause Crunch", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Pause Bicycle Crunch", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Pause Reverse Crunch", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Pause Sit-Up", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Pause Plank", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Pause Side Plank", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Pause Dead Bug", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Pause Bird Dog", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Pause Hanging Knee Raise", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Pause Hanging Leg Raise", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Pause Ab Wheel Rollout", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Pause Cable Wood Chop", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Pause Pallof Press", "Core", "Bodyweight", "Core", "Intermediate", "deadlift"),
    new Exercise("Pause Kettlebell Swing", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift"),
    new Exercise("Pause Kettlebell Clean", "Full Body", "Kettlebell", "Full Body", "Intermediate", "deadlift")
  ));
  private ExerciseData() {}
}